### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by tlogan2000**

### CODE REVIEW

**Comment by tlogan2000** [comment]
@david Flagged you on this as I thought we could pull bits and pieces for the 'fiches' related to ECCC call

**Comment by tlogan2000** [comment]
@aulemahal @Zeitsperre   first bit of desc for choice of ERA5-land ready for review.  Fancy markdown tricks / suggestions more than welcome.

**Comment by aulemahal** [comment]
Just pushed a few esthetic fixes as well as:

Use name "ESPO-R5 v1.0" (with the 5). 
Use AHCCD (and not DCCAH).

**Comment by huard** [comment]
Ahh, sorry guys. I pulled this branch into my main, so when I pushed, it merged automatically.

**Comment by tlogan2000** [comment]
ok no worries

**Comment by tlogan2000** [comment]
@huard your adds as well as initial sdba methods should be in `update_readme` branch

**Pull request merged**
